### ISSUE TITLE
iwt  ---   OverflowError: int too large to convert to float

### ISSUE THREAD

**Issue by chlangley** [tskit-dev/tsdate#206]
Hello:

In trying to tsdate a sample of 1600 humans for an entire chromosome we got the error below.
Any clue what we might have done wrong?
Is there an optional setting to avoid this issue?
I am rereading your paper for a clue.

Thanks for any help.
Cheers,
Chuck

```
| => tsdate -V
tsdate 0.1.4

| => tsdate date -p -v 1 -t 20 mAnc.trees hmX_dated.ts 10000
Find Node Spans:   2%|###                                                                                                                                          | 14569/664514 [1:32:12<68:33:28,  2.63it/s]
TipCount:   0%|                                                                                                                                                                        | 0/3 [1:32:12<?, ?it/s]
Traceback (most recent call last):
  File "/home/chuck/.local/bin/tsdate", line 8, in <module>
    sys.exit(main())
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/__main__.py", line 5, in main
    cli.tsdate_main()
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/cli.py", line 220, in tsdate_main
    args.runner(args)
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/cli.py", line 190, in run_date
    dated_ts = tsdate.date(
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/core.py", line 980, in date
    tree_sequence, dates, _, timepoints, eps, nds = get_dates(
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/core.py", line 1048, in get_dates
    priors = prior.build_grid(
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/prior.py", line 1045, in build_grid
    span_data = SpansBySamples(contmpr_ts, progress=progress)
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/prior.py", line 438, in __init__
    ) = self.first_pass()
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/prior.py", line 686, in first_pass
    if save_to_spans(prev_tree, node, num_fixed_at_0_treenodes) is None:
  File "/home/chuck/.local/lib/python3.9/site-packages/tsdate/prior.py", line 559, in save_to_spans
    iwt = wt / (wt - 1.0)  # 1/iwt from below
OverflowError: int too large to convert to float
```

**Comment by hyanwong** [comment]
Hmm, this implies that `unary_nodes_above` is very large, which seems like a bad thing.

You shouldn't get this if you fully simplify the `hmX_dated.ts` tree sequence before dating, I think. Can you try that?

**Comment by chlangley** [comment]
Yes.  After 'simplifying'  it ran straight thru.  Now to investigate results! ;)  thanks.
