### ISSUE TITLE
Bringing checks to the front of execution.

### ISSUE THREAD

**Issue by barneyhill** [tskit-dev/tsdate#320]
I've encountered two issues that have caused execution to be terminated many hours in. These checks should be done as soon as possible - I'll move them to the beginning of [tsdate.date](https://github.com/tskit-dev/tsdate/blob/main/tsdate/core.py#L1197).

Errors I encountered:
```

I was a bit forgetful and forgot to simplify before running... Might be worth adding in the unary node check at the beginning prior to finding the node spans.

(tsinfer) 2 dnanexus@job-GZKXQQjJg8JzQ8fgYXPGgfb2:~/ukb/workflow-dask$ tsdate date UKB_EUR-chr21-filter_minimal-truncate-0.4-0.6-1-mm0-processed.trees UKB_EUR-chr21-filter_minimal-truncate-0.4-0.6-1-mm0-processed-dated.trees 10000 -m 1e-8 --method variational_gamma --progress -t 192


Find Node Spans: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11959/11959 [2:28:52<00:00,  1.34it/s]
TipCount:   0%|                                                                                                                                           | 0/3 [2:28:52<?, ?it/s]
Traceback (most recent call last):
  File "/home/dnanexus/ukb/tsinfer/bin/tsdate", line 8, in <module>
    sys.exit(main())
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/__main__.py", line 5, in main
    cli.tsdate_main()
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/cli.py", line 220, in tsdate_main
    args.runner(args)
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/cli.py", line 190, in run_date
    dated_ts = tsdate.date(
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/core.py", line 1010, in date
    tree_sequence, dates, posteriors, timepoints, eps, nds = get_dates(
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/core.py", line 1085, in get_dates
    priors = prior.build_grid(
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/prior.py", line 1051, in build_grid
    span_data = SpansBySamples(contmpr_ts, progress=progress)
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/prior.py", line 438, in __init__
    ) = self.first_pass()
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/prior.py", line 715, in first_pass
    raise ValueError(
ValueError: The input tree sequence has unary nodes: tsdate currently requires that these are removed using `simplify(keep_unary=False)`

```

```
(tsinfer) dnanexus@job-GZKXQQjJg8JzQ8fgYXPGgfb2:~/ukb/workflow-dask$ tsdate date UKB_EUR-chr21-filter_minimal-truncate-0.4-0.6-1-mm0-processed-simplified.trees UKB_EUR-chr21-filt
er_minimal-truncate-0.4-0.6-1-mm0-processed-simplified-dated.trees 10000 -m 1e-8 --method variational_gamma --progress -t 96
Find Node Spans: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11959/11959 [2:25:15<00:00,  1.37it/s]
TipCount: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [2:25:15<00:00, 2905.32s/it]
2023-10-04 16:45:46,093 WARNING Initialising your tsdate installation by creating a user cache of conditional coalescent prior values for 1000 tips
Find Mixture Priors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 669539/669539 [00:03<00:00, 175382.99it/s]
Assign Prior to Each Node: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 669539/669539 [01:08<00:00, 9759.70it/s]
Precalculating Likelihoods: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 281078/281078 [00:58<00:00, 4770.05it/s]
Inside: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 669539/669539 [8:45:38<00:00, 21.23it/s]
Traceback (most recent call last):
  File "/home/dnanexus/ukb/tsinfer/bin/tsdate", line 8, in <module>
    sys.exit(main())
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/__main__.py", line 5, in main
    cli.tsdate_main()
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/cli.py", line 220, in tsdate_main
    args.runner(args)
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/cli.py", line 190, in run_date
    dated_ts = tsdate.date(
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/core.py", line 1010, in date
    tree_sequence, dates, posteriors, timepoints, eps, nds = get_dates(
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/core.py", line 1142, in get_dates
    raise ValueError(
ValueError: estimation method must be either 'inside_outside' or 'maximization'
```

**Comment by barneyhill** [comment]
I've added two initial checks at the beginning of core.py. There are two potential issues here:
1. Is there some kind of global store of all valid methods I could reference instead of explicitly defining this?
2. Looping through every tree to check for unary nodes could be inefficient on large trees - is there a faster way of doing this?

**Comment by hyanwong** [comment]
> I've added two initial checks at the beginning of core.py. 

Thanks @barneyhill 

> There are two potential issues here:
> 1. Is there some kind of global store of all valid methods I could reference instead of explicitly defining this?

Normally in tskit we stick it into a checking function at the top of the file:

https://github.com/tskit-dev/tskit/blob/53ca1d26c89d060f9e2bc5aab77c9b50796013db/python/tskit/drawing.py#L145

> 2. Looping through every tree to check for unary nodes could be inefficient on large trees - is there a faster way of doing this?

I think that's why I performed the check where it was relevant. But I think the array access should be fast, so this isn't really a problem. Note, however, that you *can* date tree sequences that have nodes with unary segments, as long as you specify a prior with `allow_unary=True`. So I think this check should go in the prior construction function instead?
