### ISSUE TITLE
approx.py b<0

### ISSUE THREAD

**Issue by barneyhill** [tskit-dev/tsdate#323]
I've been running tsdate on the TTN gene region (chr2), again with a MAF>0.001 filter so only 517 sites. I've encountered this error - any sense of what could be wrong here? Many thanks.

```
(tsinfer) dnanexus@job-GZVPjpQJg8Jq7vKz2x2KbP8p:~/ukb/workflow-dask$ tsdate date data/trees/UKB_EUR-chr2-filter_minimal/UKB_EUR-chr2-filter_minimal-truncate-0.4-0.6-1-mm0-post-processed-simplified.trees data/trees/UKB_EUR-chr2-filter_minimal/UKB_EUR-chr2-filter_minimal-truncate-0.4-0.6-1-mm0-post-processed-simplified-dated.trees 10000 -m 1e-8 --method variational_gamma --progress
Find Node Spans: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 517/517 [00:52<00:00,  9.92it/s]
TipCount: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:52<00:00, 17.45s/it]
2023-10-09 08:26:12,075 WARNING Initialising your tsdate installation by creating a user cache of conditional coalescent prior values for 1000 tips
Find Mixture Priors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6592/6592 [00:00<00:00, 153389.14it/s]
Expectation Propagation:   0%|                                                                                                                                                                | 0/20 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/dnanexus/ukb/tsinfer/bin/tsdate", line 8, in <module>
    sys.exit(main())
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/__main__.py", line 5, in main
    cli.tsdate_main()
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/cli.py", line 236, in tsdate_main
    args.runner(args)
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/cli.py", line 217, in run_date
    dated_ts = tsdate.date(ts, args.mutation_rate, args.population_size, **params)
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/core.py", line 1309, in date
    tree_sequence, dates, posteriors, timepoints, eps, nds, lik = variational_dates(
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/core.py", line 1631, in variational_dates
    dynamic_prog.iterate(iter_num=it, max_shape=max_shape)
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/core.py", line 1115, in iterate
    self.propagate(
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/core.py", line 1067, in propagate
    ) = approx.gamma_projection(*parent_cavity, *child_cavity, *edge_lik)
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/approx.py", line 280, in gamma_projection
    logconst, t_i, ln_t_i, t_j, ln_t_j = sufficient_statistics(
  File "/home/dnanexus/ukb/tsinfer/lib/python3.9/site-packages/tsdate/approx.py", line 183, in sufficient_statistics
    assert b > 0
AssertionError
```

**Comment by barneyhill** [comment]
inside-outside completes successfully
```
(tsinfer) 1 dnanexus@job-GZVPjpQJg8Jq7vKz2x2KbP8p:~/ukb/workflow-dask$ tsdate date data/trees/UKB_EUR-chr2-filter_minimal/UKB_EUR-chr2-filter_minimal-truncate-0.4-0.6-1-mm0-post-processed-simplified.trees data/trees/UKB_EUR-chr2-filter_minimal/UKB_EUR-chr2-filter_minimal-truncate-0.4-0.6-1-mm0-post-processed-simplified-dated.trees 10000 -m 1e-8 --method inside_outside --progress
Find Node Spans: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 517/517 [00:51<00:00, 10.01it/s]
TipCount: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:51<00:00, 17.30s/it]
Find Mixture Priors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6592/6592 [00:00<00:00, 143148.53it/s]
Precalculating Likelihoods: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3415/3415 [00:00<00:00, 4079.10it/s]
Inside: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6592/6592 [01:56<00:00, 56.40it/s]
Outside: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 840739/840739 [00:13<00:00, 63927.97it/s]
Constrain Ages: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6592/6592 [00:00<00:00, 132700.05it/s]
```

**Comment by hyanwong** [comment]
This is a question for @nspope, but my guess would be that with that few sites (how many samples is this?), there simply isn't enough information to get reasonable branch length estimates, so the EP algorithm hits a pathological area of parameter space.

**Comment by nspope** [comment]
Oh, I've run into this recently working on single tree dating for Relate. When there's not much data, sometimes there are invalid updates on the first forward pass. In which case, the update can be skipped, and it'll get fixed on the backward pass.

I have a feature branch with this already implemented -- @barneyhill if you're still willing to kick the wheels on this (and thanks for doing so, BTW), ping me on slack and I can point you towards this?

**Comment by hyanwong** [comment]
I'm hitting this now too (latest tsdate main branch):

<img width="1069" alt="Screenshot 2023-11-17 at 11 11 53" src="https://github.com/tskit-dev/tsdate/assets/4699014/f252f9ec-52f8-4b2e-9603-ddd0c01e4d04">

**Comment by barneyhill** [comment]
Ah great - many thanks!
